apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Port your frontend is listening on
  type: LoadBalancer  # Use LoadBalancer for external access
